apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-nginx
  namespace: argocd
spec:
  project: default
  source:
    # Usaremos el repo de ejemplos de ArgoCD que tiene un Nginx básico
    repoURL: https://github.com/resil3nt/LabsDevOps.git
    targetRevision: HEAD
    path: guestbook # Aunque se llame guestbook, este ejemplo despliega un Nginx visual
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
