apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-wordpress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/resil3nt/LabsDevOps.git
    targetRevision: HEAD
    path: wordpress
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
