apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: password-db-k8s
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: mi-secreto-final # Nombre que tendrá el secreto en K8s
    creationPolicy: Owner
  data:
  - secretKey: password  # El nombre de la 'llave' dentro de K8s
    remoteRef:
      key: db-pass       # El nombre que pusiste en Vault
      property: password # La propiedad dentro del JSON de Vault
